pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP5WXw7Y3m9iRtTsqDNhDPAFdHU -T \
            target/bio*.jar \
            "http://54.86.238.81:8081/artifactory/Geolocation/Geo/bio_${BUILD_ID}.jar"'
        }
    }
   }
}